version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: App_cat
          command: echo App_cat.

      - run:
          name: Print the Current Time
          command: date
